version: "3.3"
services:
  certs: 
    image: "${CERTS_IMAGE}"
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl:/etc/letsencrypt

  site:
    image: "${SITE_IMAGE}"
    env_file:
      - platform.env
    depends_on:
      - certs

  store:
    image: "${STORE_IMAGE}"
    env_file:
      - platform.env
    depends_on:
      - certs

  chain:
    image: "${CHAIN_IMAGE}"
    ports:
      - "8080:8080"
      - "8180:8180"
      - "8545:8545"
      - "8546:8546"
    volumes:
      - ~/.dragon/parity/:/root/.local/share/io.parity.ethereum/
    env_file:
      - platform.env
    command: ["--ws-interface", "all", "--ws-origins", "all", "--ws-hosts", "all", "--jsonrpc-hosts", "all", "--ui-interface", "0.0.0.0", "--ui-hosts", "all", "--ui-no-validation"]

  api:
    image: "${API_IMAGE}"
    env_file:
      - platform.env
    depends_on:
      - certs
      - store
      - chain
    links:
      - store
      - chain

  proxy:
    image: "${PROXY_IMAGE}"
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl/nginx-certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certs
      - site
      - api
    links:
      - certs
      - site
      - api
 
