version: "3.3"
services:
  certs: 
    image: "${DOCKER_REGISTRY_BASE}/dragoncert:${CERTS_VERSION}"
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl:/etc/letsencrypt

  site:
    image: "${DOCKER_REGISTRY_BASE}/dragonsite:${SITE_VERSION}"
    env_file:
      - platform.env
    depends_on:
      - certs

  store:
    image: "${DOCKER_REGISTRY_BASE}/dragonstore:${STORE_VERSION}"
    env_file:
      - platform.env
    depends_on:
      - certs

  chain:
    image: "${DOCKER_REGISTRY_BASE}/dragonchain:${CHAIN_VERSION}"
    ports:
      - "8080:8080"
      - "8545:8545"
      - "8180:8180"
    env_file:
      - platform.env

  socket:
    image: "${DOCKER_REGISTRY_BASE}/dragonsocket:${SOCKET_VERSION}"
    env_file:
      - platform.env
    depends_on:
      - certs
      - store
      - chain
    links:
      - store
      - chain

  proxy:
    image: "${DOCKER_REGISTRY_BASE}/dragonproxy:${PROXY_VERSION}"
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl/nginx-certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certs
      - site
      - socket
    links:
      - certs
      - site
      - socket
 
