version: "3.3"
services:
  certs: 
    build:
      DragonCerts
    image: dragon-certs
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl:/etc/letsencrypt

  site:
    build:
      DragonSite
    image: dragon-site
    env_file:
      - platform.env
    depends_on:
      - certs

  store:
    build:
      DragonStore
    image: dragon-store
    env_file:
      - platform.env
    depends_on:
      - certs

  socket:
    build:
      DragonSockets
    image: dragon-socket
    env_file:
      - platform.env
    depends_on:
      - certs
      - store
    links:
      - store

  proxy:
    build:
      DragonProxy
    image: dragon-proxy
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl/nginx-certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certs
      - site
      - socket
    links:
      - certs
      - site
      - socket
 
