version: "3.3"
services:
  certs: 
    build:
      DragonCerts
    image: "${DOCKER_REGISTRY_BASE}/dragon-certs:${CERTS_VERSION}"
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl:/etc/letsencrypt

  site:
    build:
      DragonSite
    image: "${DOCKER_REGISTRY_BASE}/dragon-site:${SITE_VERSION}"
    env_file:
      - platform.env
    depends_on:
      - certs

  store:
    build:
      DragonStore
    image: "${DOCKER_REGISTRY_BASE}/dragon-store:${STORE_VERSION}"
    env_file:
      - platform.env
    depends_on:
      - certs

  parity:
    image: docker.io/parity/parity:v1.7.2
    ports:
      - "8080:8080"
      - "8545:8545"
      - "8180:8180"
    env_file:
      - platform.env

  socket:
    build:
      DragonSockets
    image: "${DOCKER_REGISTRY_BASE}/dragon-socket:${SOCKET_VERSION}"
    env_file:
      - platform.env
    depends_on:
      - certs
      - store
      - parity
    links:
      - store
      - parity

  proxy:
    build:
      DragonProxy
    image: "${DOCKER_REGISTRY_BASE}/dragon-proxy:${PROXY_VERSION}"
    env_file:
      - platform.env
    volumes:
      - ~/.dragon/ssl/nginx-certs:/etc/nginx/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - certs
      - site
      - socket
    links:
      - certs
      - site
      - socket
 
